name: SuperSnyk 🦸
description: "Detects automated Snyk PRs and adds 'snyk' label. Combines PRs with the 'snyk' label into a single SuperSnyk 🦸 PR. If a SuperSnyk 🦸 PR already exists, it will be updated."
inputs:
  repo-token:
    description: "GitHub token i.e. secrets.GITHUB_TOKEN"
    required: true
    default: "CHANGE_ME"

runs:
  using: "composite"
  steps:
    - uses: TimonVS/pr-labeler-action@v3
      name: Detect and label Snyk PR for 🦸 SuperSnyk
      with:
        configuration-path: ${{ format('{0}/pr-labeler.yml, env.GITHUB_ACTION_PATH) }}
      env:
        GITHUB_TOKEN: ${{ inputs.repo-token }}

    - uses: 8BitJonny/gh-get-current-pr@2.0.0
      id: PR
      with:
        github-token: ${{ inputs.repo-token }}
        sha: ${{ github.event.pull_request.head.sha }}
        filterOutClosed: true
        filterOutDraft: 1

    - run: echo "PR LABEL ${prLabel}"
      shell: bash
      if: success() && steps.PR.outputs.number
      env:
        prNumber: ${{ steps.PR.outputs.number }}
        prJSON: ${{ steps.PR.outputs.pr }}
        prLabel: ${{ steps.PR.outputs.pr_labels }}

    - uses: actions/checkout@v2
      with:
        ref: main
        fetch-depth: 0

    - uses: bobvanderlinden/combine-pull-requests@v3
      with:
        label: snyk
        repo-token: ${{ inputs.repo-token }}

    - name: Get Snyk PRs metadata
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.repo-token }}
      run: |
        chmod +x $GITHUB_ACTION_PATH/get-snyk-prs-metadata.sh
        $GITHUB_ACTION_PATH/get-snyk-prs-metadata.sh

    - name: Create SuperSnyk 🦸 PR
      uses: peter-evans/create-pull-request@v4
      with:
        title: 🦸 SuperSnyk
        body: "🦸 SuperSnyk PR created with [create-pull-request](https://github.com/peter-evans/create-pull-request)\n${{ env.SUPERSNYK_PR_BODY }}"
